services:
  - type: web
    name: jerkie-man-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build --workspace=shared && npm run build --workspace=server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 18723
